spring:
  application:
    name: order
  cloud:
    nacos:
      discovery:
        username: naocs
        password: nacos
        server-addr: 127.0.0.1:8848
        namespace: public
server:
  port: 9001