spring:
  application:
    name: api
  cloud:
    nacos:
      discovery:
        username: naocs
        password: nacos
        server-addr: 127.0.0.1:8848
        namespace: public
server:
  port: 9000
feign:
  sentinel:
    enabled: true
